/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package add_page;

import globals.GlobalVariable;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

import javax.swing.SpinnerDateModel;

/**
 *
 * @author zeyad
 */
public class AddDialogView extends javax.swing.JDialog {

    AddController controller;

    public AddDialogView(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        controller = new AddController(this);

        SpinnerDateModel model = new SpinnerDateModel();
        spnHiredate.setModel(model);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        buttonGroupStatus = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spnHiredate = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        cmbDept = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rbtnSingle = new javax.swing.JRadioButton();
        rbtnMarried = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setLayout(new java.awt.GridLayout(7, 2, 0, 10));

        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jPanel1.add(txtName);

        jLabel2.setText("ID");
        jPanel1.add(jLabel2);
        jPanel1.add(txtID);

        jLabel3.setText("Hiredate");
        jPanel1.add(jLabel3);

        spnHiredate.setModel(new javax.swing.SpinnerDateModel());
        spnHiredate.setEditor(new javax.swing.JSpinner.DateEditor(spnHiredate, "dd-MM-yyyy"));
        jPanel1.add(spnHiredate);

        jLabel4.setText("Department");
        jPanel1.add(jLabel4);

        cmbDept.setBackground(btnAdd.getBackground());
        cmbDept.setModel(new DefaultComboBoxModel(GlobalVariable.departments.toArray(new String[0])));
        jPanel1.add(cmbDept);

        jLabel5.setText("Gender");
        jPanel1.add(jLabel5);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        buttonGroupGender.add(rbtnMale);
        rbtnMale.setSelected(true);
        rbtnMale.setText("Male");
        jPanel2.add(rbtnMale);

        buttonGroupGender.add(rbtnFemale);
        rbtnFemale.setText("Female");
        jPanel2.add(rbtnFemale);

        jPanel1.add(jPanel2);

        jLabel6.setText("Social Status");
        jPanel1.add(jLabel6);

        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        buttonGroupStatus.add(rbtnSingle);
        rbtnSingle.setSelected(true);
        rbtnSingle.setText("Single");
        jPanel3.add(rbtnSingle);

        buttonGroupStatus.add(rbtnMarried);
        rbtnMarried.setText("Married");
        jPanel3.add(rbtnMarried);

        jPanel1.add(jPanel3);

        jLabel7.setText("Address");

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        btnAdd.setBackground(new java.awt.Color(71, 205, 93));
        btnAdd.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            controller.addEmployee();
            // TODO add your handling code here:
        } catch (IOException ex) {
            Logger.getLogger(AddDialogView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.ButtonGroup buttonGroupStatus;
    protected javax.swing.JComboBox<String> cmbDept;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JRadioButton rbtnFemale;
    protected javax.swing.JRadioButton rbtnMale;
    protected javax.swing.JRadioButton rbtnMarried;
    protected javax.swing.JRadioButton rbtnSingle;
    protected javax.swing.JSpinner spnHiredate;
    protected javax.swing.JTextArea txtAddress;
    protected javax.swing.JTextField txtID;
    protected javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
